"""Turn results/*.json into the markdown tables used in the README.

Kept as a script rather than hand-written tables so the README can never drift
from what was actually measured.

    python -m src.report --tags base finetuned > results/tables.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


def load(tag: str) -> Dict:
    path = Path("results") / f"{tag}.json"
    if not path.exists():
        raise SystemExit(f"missing {path} — run src.evaluate --tag {tag} first")
    return json.loads(path.read_text())


def index(payload: Dict) -> Dict[tuple, Dict]:
    return {(r["corruption"], r["severity"]): r for r in payload["results"]}


def delta(new: float, old: float) -> str:
    d = new - old
    return f"{d:+.3f}" if abs(d) >= 0.0005 else "0.000"


def headline(base: Dict, tuned: Dict) -> List[str]:
    b, t = index(base).get(("clean", 0)), index(tuned).get(("clean", 0))
    if not (b and t):
        return []
    rows = [
        "| Model | Field F1 | Exact match | Parse rate |",
        "| --- | --- | --- | --- |",
        f"| Qwen2-VL-2B (base, 4-bit) | {b['field_f1']:.3f} | {b['exact_match']:.3f} | {b['parse_rate']:.3f} |",
        f"| + QLoRA fine-tune | **{t['field_f1']:.3f}** | **{t['exact_match']:.3f}** | **{t['parse_rate']:.3f}** |",
        f"| Delta | {delta(t['field_f1'], b['field_f1'])} | {delta(t['exact_match'], b['exact_match'])} | {delta(t['parse_rate'], b['parse_rate'])} |",
    ]
    return rows


def robustness(payload: Dict) -> List[str]:
    idx = index(payload)
    clean = idx.get(("clean", 0))
    rows = [
        "| Corruption | Severity | Field F1 | Δ vs clean | Exact match |",
        "| --- | --- | --- | --- | --- |",
    ]
    for (name, sev), r in idx.items():
        if name == "clean":
            continue
        d = delta(r["field_f1"], clean["field_f1"]) if clean else "—"
        rows.append(
            f"| {name} | {sev} | {r['field_f1']:.3f} | {d} | {r['exact_match']:.3f} |"
        )
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tags", nargs="+", default=["base", "finetuned"])
    args = ap.parse_args()

    payloads = {tag: load(tag) for tag in args.tags}
    any_payload = next(iter(payloads.values()))

    print(f"<!-- generated by src/report.py — do not edit by hand -->")
    print(f"\nEvaluated on CORD-v2 `{any_payload['split']}`, "
          f"n={any_payload['n_samples']}, greedy decoding.\n")

    if "base" in payloads and "finetuned" in payloads:
        print("### Clean-set accuracy\n")
        print("\n".join(headline(payloads["base"], payloads["finetuned"])))

    for tag, payload in payloads.items():
        print(f"\n### Robustness sweep — {tag}\n")
        print("\n".join(robustness(payload)))


if __name__ == "__main__":
    main()
